{{- if .Values.quota.enabled }}
apiVersion: v1
kind: ResourceQuota
metadata:
  name: {{ include "ns.name" . }}-quota
  namespace: {{ include "ns.name" . }}
  labels: {{- include "ns.labels" . | nindent 4 }}
spec:
  hard:
    requests.cpu: {{ .Values.quota.requestsCpu | quote }}
    requests.memory: {{ .Values.quota.requestsMemory | quote }}
    limits.cpu: {{ .Values.quota.limitsCpu | quote }}
    limits.memory: {{ .Values.quota.limitsMemory | quote }}
    pods: {{ .Values.quota.pods | quote }}
    persistentvolumeclaims: {{ .Values.quota.persistentVolumeClaims | quote }}
{{- end }}
