apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "cronjob.fullname" . }}
  labels: {{- include "cronjob.labels" . | nindent 4 }}
spec:
  schedule: {{ .Values.schedule | quote }}
  timeZone: {{ .Values.timeZone | quote }}
  concurrencyPolicy: {{ .Values.concurrencyPolicy }}
  startingDeadlineSeconds: {{ .Values.startingDeadlineSeconds }}
  successfulJobsHistoryLimit: {{ .Values.successfulJobsHistoryLimit }}
  failedJobsHistoryLimit: {{ .Values.failedJobsHistoryLimit }}
  suspend: {{ .Values.suspend }}
  jobTemplate:
    spec:
      backoffLimit: {{ .Values.backoffLimit }}
      activeDeadlineSeconds: {{ .Values.activeDeadlineSeconds }}
      template:
        metadata:
          labels: {{- include "cronjob.labels" . | nindent 12 }}
          {{- with .Values.podAnnotations }}
          annotations: {{- toYaml . | nindent 12 }}
          {{- end }}
        spec:
          restartPolicy: Never
          {{- if .Values.serviceAccount.create }}
          serviceAccountName: {{ include "cronjob.fullname" . }}
          {{- end }}
          containers:
            - name: job
              image: {{ include "cronjob.image" . }}
              imagePullPolicy: {{ .Values.image.pullPolicy }}
              env:
                - name: LEMBOS_COMPONENT
                  value: {{ .Values.lembos.component | quote }}
                - name: LEMBOS_ENVIRONMENT
                  value: {{ .Values.lembos.environment | quote }}
                - name: LEMBOS_STAMP
                  value: {{ .Values.lembos.stamp | quote }}
                {{- range $key, $value := .Values.config }}
                - name: {{ $key }}
                  value: {{ $value | quote }}
                {{- end }}
                {{- range $handle, $binding := .Values.resourceBindings }}
                - name: {{ $handle | upper | replace "-" "_" }}_URL
                  valueFrom:
                    secretKeyRef:
                      name: {{ $binding.secretRef | replace "/" "-" }}
                      key: url
                {{- end }}
              resources: {{- include "cronjob.resources" . | nindent 16 }}
          {{- with .Values.nodeSelector }}
          nodeSelector: {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.tolerations }}
          tolerations: {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.affinity }}
          affinity: {{- toYaml . | nindent 12 }}
          {{- end }}
